name: Daily Update Action List

on:
  schedule:
    # 日本時間 2:24 に実行
    - cron: "35 4 * * *"

env:
  NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
  ACTION_LIST_MASTER_DB_ID: ${{ secrets.ACTION_LIST_MASTER_DB_ID }}
  ACTION_LIST_RECORD_DB_ID: ${{ secrets.ACTION_LIST_RECORD_DB_ID }}

jobs:
  update_action_list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Action List
        shell: bash
        run: |
          ./scripts/get-master-action-list.sh | \
              jq -c '.results[].properties | {category: .category.select.name, action: .action.title[0].text.content, point: .point.number}' | \
              sed -e 's/"/\\"/g' | \
              xargs -n1 bash -c './scripts/insert-action-into-notion-db.sh $(echo "$0" | jq .category) $(echo "$0" | jq .action) $(echo "$0" | jq .point) $(TZ=Asia/Tokyo date "+%Y-%m-%d")'
